### ISSUE TITLE
problems with A4.5 and Android 6.

### ISSUE THREAD

**Issue by Andy2244** [TeamWin/android_device_bq_dendeone#1]
Hi,

we can't get any TWRP version to work with the Android 6 firmwares of the bq A4.5. The only way to get into TWRP is to use the 5.1 LK.BIN, but you need to reflash the 6.0 version afterwards or Android wont boot into the system.

Flashing TWRP 3.0 or 2.8.7.0 either results in a infinite reboot loop or the org. recovery is somehow restored after a few reboots.

TWRP works fine using the Android 5.1 firmwares, so the 6.0 bootloader/kernel seems to-be incompatibel.

thx
Andy

**Comment by Kra1o5** [comment]
@Andy2244 it will be fixed in 3.0.0-1 .

Greetings

**Comment by Kra1o5** [comment]
@Andy2244 , 

Sorry, fixed in 3.0.0-2 .

Greetings
